# Generated by Django 4.1.3 on 2023-03-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['created_date']},
        ),
    ]
