# Generated by Django 4.1.3 on 2023-03-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
    ]
