# Generated by Django 4.1.3 on 2023-03-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_discussion_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='post', to='post.tag'),
        ),
    ]
