# Generated by Django 4.1.3 on 2023-03-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='post.discussion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='post.tag'),
        ),
    ]
