# Generated by Django 4.1.3 on 2023-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_auctionhistory_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='NOT_STANDARD', max_length=20),
        ),
    ]
