# Generated by Django 4.1.3 on 2023-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlImages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
